"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_1 = require("react");
var HomePage = /** @class */ (function (_super) {
    __extends(HomePage, _super);
    function HomePage(props) {
        var _this = _super.call(this, props) || this;
        _this.state = {};
        return _this;
    }
    HomePage.prototype.render = function () {
        return (React.createElement(React.Fragment, null,
            React.createElement("section", { className: "main-wrapper xs-col-12" },
                React.createElement("div", { id: "homepage" },
                    React.createElement("div", { className: "wrapper wrapper__buildGuides" },
                        React.createElement("section", { className: "build-guides xs-col-11 lg-col-9 xl-col-8 xs-mx-auto" },
                            React.createElement("div", { className: "guides__info" },
                                React.createElement("h1", null, "Build Guides"),
                                React.createElement("p", null, "Building your own PC and need ideas on where to get started? Explore our build guides which cover systems for a variety of use-cases and budgets."),
                                React.createElement("a", { href: "/guide/", className: "button" }, "View the Build Guides")),
                            React.createElement("li", { className: "guideGroup guideGroup__card" },
                                React.createElement("a", { href: "/guide/PB6MnQ/entry-level-amd-gaming-build", className: "guideGroup__target" }),
                                React.createElement("div", { className: "guideGroup__content--wrapper1" },
                                    React.createElement("h1", { className: "guide__title" }, "Entry Level AMD Gaming Build"),
                                    React.createElement("ul", { className: "guide__keyProducts list-unstyled" },
                                        React.createElement("li", null, "AMD Ryzen 5 2600"),
                                        React.createElement("li", null, "Parametric Video Card (Chipset: GeForce GTX 1650 SUPER)"),
                                        React.createElement("li", null, "Cougar MX330 ATX Mid Tower"))),
                                React.createElement("div", { className: "guideGroup__content--wrapper2" },
                                    React.createElement("div", { className: "guide__numbers" },
                                        React.createElement("p", { className: "guide__price" }, "$582.93"),
                                        React.createElement("p", { className: "guide__links" },
                                            React.createElement("span", { className: "guide__link--comments" },
                                                React.createElement("svg", { className: "icon shape-comment" },
                                                    React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                "189"))),
                                    React.createElement("ul", { className: "guide__images list-unstyled" },
                                        React.createElement("li", { className: "guide__images--1" },
                                            React.createElement("img", { src: "https://images-na.ssl-images-amazon.com/images/I/51N2BQA3cBL.jpg" })),
                                        React.createElement("li", { className: "guide__images--2" },
                                            React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/product/55aea2dd64e2e3a3e3b1d678048d8d76.256p.jpg" })),
                                        React.createElement("li", { className: "guide__images--3" },
                                            React.createElement("img", { src: "https://m.media-amazon.com/images/I/41zgLYpzn1L.jpg" }))))),
                            React.createElement("li", { className: "guideGroup guideGroup__card" },
                                React.createElement("a", { href: "/guide/s4V323/excellent-intel-gamingstreaming-build", className: "guideGroup__target" }),
                                React.createElement("div", { className: "guideGroup__content--wrapper1" },
                                    React.createElement("h1", { className: "guide__title" }, "Excellent Intel Gaming/Streaming Build"),
                                    React.createElement("ul", { className: "guide__keyProducts list-unstyled" },
                                        React.createElement("li", null, "Intel Core i5-10600K"),
                                        React.createElement("li", null, "Parametric Video Card (Chipset: GeForce RTX 3070)"),
                                        React.createElement("li", null, "Corsair 4000D Airflow ATX Mid Tower"))),
                                React.createElement("div", { className: "guideGroup__content--wrapper2" },
                                    React.createElement("div", { className: "guide__numbers" },
                                        React.createElement("p", { className: "guide__price" }, "$1312.54"),
                                        React.createElement("p", { className: "guide__links" },
                                            React.createElement("span", { className: "guide__link--comments" },
                                                React.createElement("svg", { className: "icon shape-comment" },
                                                    React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                "63"))),
                                    React.createElement("ul", { className: "guide__images list-unstyled" },
                                        React.createElement("li", { className: "guide__images--1" },
                                            React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/product/bc6e987da3fe22c616898d1d7fa3d227.256p.jpg" })),
                                        React.createElement("li", { className: "guide__images--2" },
                                            React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/product/cec5ee818776737baefc9603bdbf9391.256p.jpg" })),
                                        React.createElement("li", { className: "guide__images--3" },
                                            React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/product/200b4e048d11f6870e697e2693490cd3.256p.jpg" }))))))),
                    React.createElement("div", { className: "wrapper wrapper__completedBuilds" },
                        React.createElement("section", { className: "completed-builds xs-col-11 lg-col-9 xl-col-8 xs-mx-auto" },
                            React.createElement("section", { className: "module-subTitle" },
                                React.createElement("div", { className: "subTitle" },
                                    React.createElement("div", { className: "subTitle__header" },
                                        React.createElement("h2", null, "Completed Builds")))),
                            React.createElement("ul", { id: "userbuild_list", className: "logGrid list-unstyled" },
                                React.createElement("li", { className: "logGroup__card--featured" },
                                    React.createElement("div", { className: "featured__message" },
                                        React.createElement("p", null,
                                            React.createElement("svg", { className: "nav__icon", xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 20 24" },
                                                React.createElement("g", { "data-name": "Layer 2" },
                                                    React.createElement("g", { "data-name": "Layer 1" },
                                                        React.createElement("path", { d: "M19.08 1l-12-1H7a.62.62 0 0 0-.19 0h-.14l-.09.1-.13.07-.13.09L.45 4.17A1 1 0 0 0 0 5v17a1 1 0 0 0 .84 1l6 1H19a1 1 0 0 0 1-1V2a1 1 0 0 0-.92-1zM6 21.82l-4-.67V5.54l4-2.67zM18 22H8V2.09l10 .83z" }),
                                                        React.createElement("circle", { cx: 13, cy: 18, r: 1 }),
                                                        React.createElement("path", { d: "M17 4.6L9 4v2l8 .6v-2zM17 7.6L9 7v2l8 .6v-2z" }))))),
                                        React.createElement("h1", null, "Featured Build"),
                                        React.createElement("p", null,
                                            "Congratulations ",
                                            React.createElement("a", { href: "/user/_Rip_/" }, "_Rip_"),
                                            "!")),
                                    React.createElement("div", { className: "logGroup logGroup__card" },
                                        React.createElement("a", { href: "/b/72BZxr", className: "logGroup__target" }),
                                        React.createElement("div", { className: "logGroup__content--wrapper1" },
                                            React.createElement("p", { className: "log__author" },
                                                React.createElement("a", { href: "/user/_Rip_/", className: "userAvatar" },
                                                    React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/user/3845343.42e1e783996dc1669c451b48858a5481.256c.jpg" })),
                                                React.createElement("a", { href: "/user/_Rip_/" }, "_Rip_")),
                                            React.createElement("a", { href: "/b/72BZxr", className: "log__image", style: { backgroundImage: 'url(//cdna.pcpartpicker.com/static/forever/images/userbuild/331461.a4ad9c81e55c97936fc399a8725566f0.512.jpg)' } }),
                                            React.createElement("h1", { className: "log__title" },
                                                React.createElement("a", { href: "/b/72BZxr" }, "Master Build - Corsair Obsidian 1000d")),
                                            React.createElement("ul", { className: "log__keyProducts list-unstyled" },
                                                React.createElement("li", { className: "build__specs" }, "AMD Threadripper 3960X"),
                                                React.createElement("li", { className: "build__specs" }, "GeForce RTX 2080 Ti (x2)"))),
                                        React.createElement("div", { className: "logGroup__content--wrapper2" },
                                            React.createElement("div", { className: "log__numbers" },
                                                React.createElement("p", { className: "log__price" }, "$19405.89+"),
                                                React.createElement("p", { className: "log__links" },
                                                    React.createElement("span", { className: "log__link--followers" },
                                                        React.createElement("svg", { className: "icon shape-arrow-up" },
                                                            React.createElement("use", { xlinkHref: "#shape-arrow-up" })),
                                                        "259"),
                                                    React.createElement("span", { className: "log__link--comments" },
                                                        React.createElement("svg", { className: "icon shape-comment" },
                                                            React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                        "248")))))),
                                React.createElement("li", { className: "logGroup logGroup__card" },
                                    React.createElement("a", { href: "/b/yRMcCJ", className: "logGroup__target" }),
                                    React.createElement("div", { className: "logGroup__content--wrapper1" },
                                        React.createElement("p", { className: "log__author" },
                                            React.createElement("a", { href: "/user/Soldr/", className: "userAvatar" },
                                                React.createElement("img", { src: "/static/img/default-avatar.png" })),
                                            React.createElement("a", { href: "/user/Soldr/" }, "Soldr")),
                                        React.createElement("a", { href: "/b/yRMcCJ", className: "log__image", style: { backgroundImage: 'url(//cdna.pcpartpicker.com/static/forever/images/userbuild/334874.eee74d879b0b0054c6aacda77ba91c03.512.jpg)' } }),
                                        React.createElement("h1", { className: "log__title" },
                                            React.createElement("a", { href: "/b/yRMcCJ" }, "My best build yet")),
                                        React.createElement("ul", { className: "log__keyProducts list-unstyled" },
                                            React.createElement("li", { className: "build__specs" }, "AMD Ryzen 7 3700X"),
                                            React.createElement("li", { className: "build__specs" }, "Radeon RX 580"))),
                                    React.createElement("div", { className: "logGroup__content--wrapper2" },
                                        React.createElement("div", { className: "log__numbers" },
                                            React.createElement("p", { className: "log__price" }, "$821.93+"),
                                            React.createElement("p", { className: "log__links" },
                                                React.createElement("span", { className: "log__link--followers" },
                                                    React.createElement("svg", { className: "icon shape-arrow-up" },
                                                        React.createElement("use", { xlinkHref: "#shape-arrow-up" })),
                                                    "5"),
                                                React.createElement("span", { className: "log__link--comments" },
                                                    React.createElement("svg", { className: "icon shape-comment" },
                                                        React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                    "3"))))),
                                React.createElement("li", { className: "logGroup logGroup__card" },
                                    React.createElement("a", { href: "/b/nFp8TW", className: "logGroup__target" }),
                                    React.createElement("div", { className: "logGroup__content--wrapper1" },
                                        React.createElement("p", { className: "log__author" },
                                            React.createElement("a", { href: "/user/GaronAgrawal/", className: "userAvatar" },
                                                React.createElement("img", { src: "/static/img/default-avatar.png" })),
                                            React.createElement("a", { href: "/user/GaronAgrawal/" }, "GaronAgrawal")),
                                        React.createElement("a", { href: "/b/nFp8TW", className: "log__image", style: { backgroundImage: 'url(//cdna.pcpartpicker.com/static/forever/images/userbuild/334864.83b5210a4855a7a4b40f581d9a8b8327.512.jpg)' } }),
                                        React.createElement("h1", { className: "log__title" },
                                            React.createElement("a", { href: "/b/nFp8TW" }, "First Build")),
                                        React.createElement("ul", { className: "log__keyProducts list-unstyled" },
                                            React.createElement("li", { className: "build__specs" }, "AMD Ryzen 5 3600XT"),
                                            React.createElement("li", { className: "build__specs" }, "GeForce RTX 2060"))),
                                    React.createElement("div", { className: "logGroup__content--wrapper2" },
                                        React.createElement("div", { className: "log__numbers" },
                                            React.createElement("p", { className: "log__price" }, "$1279.27+"),
                                            React.createElement("p", { className: "log__links" },
                                                React.createElement("span", { className: "log__link--followers" },
                                                    React.createElement("svg", { className: "icon shape-arrow-up" },
                                                        React.createElement("use", { xlinkHref: "#shape-arrow-up" })),
                                                    "4"),
                                                React.createElement("span", { className: "log__link--comments" },
                                                    React.createElement("svg", { className: "icon shape-comment" },
                                                        React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                    "6"))))),
                                React.createElement("li", { className: "logGroup logGroup__card" },
                                    React.createElement("a", { href: "/b/jKx6Mp", className: "logGroup__target" }),
                                    React.createElement("div", { className: "logGroup__content--wrapper1" },
                                        React.createElement("p", { className: "log__author" },
                                            React.createElement("a", { href: "/user/Crazydamias7/", className: "userAvatar" },
                                                React.createElement("img", { src: "/static/img/default-avatar.png" })),
                                            React.createElement("a", { href: "/user/Crazydamias7/" }, "Crazydamias7")),
                                        React.createElement("a", { href: "/b/jKx6Mp", className: "log__image", style: { backgroundImage: 'url(//cdna.pcpartpicker.com/static/forever/images/userbuild/334856.5e7af080067b80c178babe8c1c5c04b2.512.jpg)' } }),
                                        React.createElement("h1", { className: "log__title" },
                                            React.createElement("a", { href: "/b/jKx6Mp" }, "My Gaming PC")),
                                        React.createElement("ul", { className: "log__keyProducts list-unstyled" },
                                            React.createElement("li", { className: "build__specs" }, "Intel Core i5-7400"),
                                            React.createElement("li", { className: "build__specs" }, "GeForce GTX 1050 Ti"))),
                                    React.createElement("div", { className: "logGroup__content--wrapper2" },
                                        React.createElement("div", { className: "log__numbers" },
                                            React.createElement("p", { className: "log__price" }, "$1133.88+"),
                                            React.createElement("p", { className: "log__links" },
                                                React.createElement("span", { className: "log__link--followers" },
                                                    React.createElement("svg", { className: "icon shape-arrow-up" },
                                                        React.createElement("use", { xlinkHref: "#shape-arrow-up" })),
                                                    "4"),
                                                React.createElement("span", { className: "log__link--comments" },
                                                    React.createElement("svg", { className: "icon shape-comment" },
                                                        React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                    "3"))))),
                                React.createElement("li", { className: "logGroup logGroup__card" },
                                    React.createElement("a", { href: "/b/6jskcf", className: "logGroup__target" }),
                                    React.createElement("div", { className: "logGroup__content--wrapper1" },
                                        React.createElement("p", { className: "log__author" },
                                            React.createElement("a", { href: "/user/NasTomkinson/", className: "userAvatar" },
                                                React.createElement("img", { src: "/static/img/default-avatar.png" })),
                                            React.createElement("a", { href: "/user/NasTomkinson/" }, "NasTomkinson")),
                                        React.createElement("a", { href: "/b/6jskcf", className: "log__image", style: { backgroundImage: 'url(//cdna.pcpartpicker.com/static/forever/images/userbuild/334855.2c2a42468645676fc90e755996fd237f.512.jpg)' } }),
                                        React.createElement("h1", { className: "log__title" },
                                            React.createElement("a", { href: "/b/6jskcf" }, "5800X + 6800XT Red Team build")),
                                        React.createElement("ul", { className: "log__keyProducts list-unstyled" },
                                            React.createElement("li", { className: "build__specs" }, "AMD Ryzen 7 5800X"),
                                            React.createElement("li", { className: "build__specs" }, "Radeon RX 6800 XT"))),
                                    React.createElement("div", { className: "logGroup__content--wrapper2" },
                                        React.createElement("div", { className: "log__numbers" },
                                            React.createElement("p", { className: "log__price" }, "$1008.39+"),
                                            React.createElement("p", { className: "log__links" },
                                                React.createElement("span", { className: "log__link--followers" },
                                                    React.createElement("svg", { className: "icon shape-arrow-up" },
                                                        React.createElement("use", { xlinkHref: "#shape-arrow-up" })),
                                                    "11"),
                                                React.createElement("span", { className: "log__link--comments" },
                                                    React.createElement("svg", { className: "icon shape-comment" },
                                                        React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                    "6"))))),
                                React.createElement("li", { className: "logGroup logGroup__card" },
                                    React.createElement("a", { href: "/b/rhdmP6", className: "logGroup__target" }),
                                    React.createElement("div", { className: "logGroup__content--wrapper1" },
                                        React.createElement("p", { className: "log__author" },
                                            React.createElement("a", { href: "/user/czvczx/", className: "userAvatar" },
                                                React.createElement("img", { src: "/static/img/default-avatar.png" })),
                                            React.createElement("a", { href: "/user/czvczx/" }, "czvczx")),
                                        React.createElement("a", { href: "/b/rhdmP6", className: "log__image", style: { backgroundImage: 'url(//cdna.pcpartpicker.com/static/forever/images/userbuild/334851.bc573305605e292d84d855144d1d14e1.512.jpg)' } }),
                                        React.createElement("h1", { className: "log__title" },
                                            React.createElement("a", { href: "/b/rhdmP6" }, "2020 build")),
                                        React.createElement("ul", { className: "log__keyProducts list-unstyled" },
                                            React.createElement("li", { className: "build__specs" }, "AMD Ryzen 9 5900X"),
                                            React.createElement("li", { className: "build__specs" }, "GeForce RTX 3080"))),
                                    React.createElement("div", { className: "logGroup__content--wrapper2" },
                                        React.createElement("div", { className: "log__numbers" },
                                            React.createElement("p", { className: "log__price" }, "$3756.47+"),
                                            React.createElement("p", { className: "log__links" },
                                                React.createElement("span", { className: "log__link--followers" },
                                                    React.createElement("svg", { className: "icon shape-arrow-up" },
                                                        React.createElement("use", { xlinkHref: "#shape-arrow-up" })),
                                                    "6"),
                                                React.createElement("span", { className: "log__link--comments" },
                                                    React.createElement("svg", { className: "icon shape-comment" },
                                                        React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                    "7"))))),
                                React.createElement("li", { className: "logGroup__action" },
                                    React.createElement("p", null,
                                        React.createElement("a", { href: "/builds/", className: "button" }, "See All Completed Builds")))))),
                    React.createElement("div", { className: "wrapper wrapper__blogPosts" },
                        React.createElement("section", { className: "blog-posts xs-col-11 lg-col-9 xl-col-8 xs-mx-auto" },
                            React.createElement("section", { className: "module-subTitle" },
                                React.createElement("div", { className: "subTitle" },
                                    React.createElement("div", { className: "subTitle__header" },
                                        React.createElement("h2", null, "Blog")))),
                            React.createElement("ul", { className: "blogGrid list-unstyled" },
                                React.createElement("li", { className: "blogGroup" },
                                    React.createElement("a", { href: "/blog/163/charity-water-completion-report-13-14-15", className: "blog__image" },
                                        React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/content/cefdf8c662bb641f1f699f08540f950b.800.450.jpg" }),
                                        React.createElement("h1", { className: "blog__title" }, "charity: water Completion Reports #13, #14, #15")),
                                    React.createElement("p", { className: "meta" },
                                        "Posted July 8, 2020 by ",
                                        React.createElement("a", { href: "/user/philip/" }, "philip")),
                                    React.createElement("p", null,
                                        "Three more ",
                                        React.createElement("a", { href: "https://charitywater.org" }, "charity: water"),
                                        " completions report arrived! Thanks to your support, we were able to fund 9 water projects in Uganda, Ethiopia, and Nepal."),
                                    React.createElement("a", { href: "/blog/163/charity-water-completion-report-13-14-15#comments", className: "blog__link--comments" },
                                        React.createElement("svg", { className: "icon shape-comment" },
                                            React.createElement("use", { xlinkHref: "#shape-comment" })),
                                        "14")),
                                React.createElement("li", { className: "blogGroup" },
                                    React.createElement("a", { href: "/blog/162/charity-water-completion-report-12", className: "blog__image" },
                                        React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/content/8816657811058a2b0ec9c7caa53ef519.800.450.jpg" }),
                                        React.createElement("h1", { className: "blog__title" }, "charity: water Completion Report #12")),
                                    React.createElement("p", { className: "meta" },
                                        "Posted Dec. 25, 2019 by ",
                                        React.createElement("a", { href: "/user/philip/" }, "philip")),
                                    React.createElement("p", null,
                                        "Our twelfth ",
                                        React.createElement("a", { href: "https://charitywater.org" }, "charity: water"),
                                        " completion report arrived! Thanks to your support, we were able to fund 14 water projects in the Maradi Region of Niger serving 6,062 people."),
                                    React.createElement("a", { href: "/blog/162/charity-water-completion-report-12#comments", className: "blog__link--comments" },
                                        React.createElement("svg", { className: "icon shape-comment" },
                                            React.createElement("use", { xlinkHref: "#shape-comment" })),
                                        "25")),
                                React.createElement("li", { className: "blogGroup" },
                                    React.createElement("a", { href: "/blog/161/laptops-added-to-pcpartpicker", className: "blog__image" },
                                        React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/content/d595291786238f15449d21458b1f229e.jpg" }),
                                        React.createElement("h1", { className: "blog__title" }, "Laptops Added to PCPartPicker")),
                                    React.createElement("p", { className: "meta" },
                                        "Posted Nov. 22, 2019 by ",
                                        React.createElement("a", { href: "/user/philip/" }, "philip")),
                                    React.createElement("p", null,
                                        "Today we're pleased to announce that PCPartPicker is now listing ",
                                        React.createElement("a", { href: "/products/laptop/" }, "traditional and 2-in-1 laptops"),
                                        "."),
                                    React.createElement("a", { href: "/blog/161/laptops-added-to-pcpartpicker#comments", className: "blog__link--comments" },
                                        React.createElement("svg", { className: "icon shape-comment" },
                                            React.createElement("use", { xlinkHref: "#shape-comment" })),
                                        "49"))),
                            React.createElement("div", { className: "blog__button" },
                                React.createElement("a", { href: "/blog/", className: "button button--small" }, "See More Blog Posts"))))))));
    };
    return HomePage;
}(react_1.Component));
exports.default = HomePage;
//# sourceMappingURL=HomePage.js.map