"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_1 = require("react");
var HomePage = /** @class */ (function (_super) {
    __extends(HomePage, _super);
    function HomePage(props) {
        var _this = _super.call(this, props) || this;
        _this.state = {};
        return _this;
    }
    HomePage.prototype.render = function () {
        return (React.createElement(React.Fragment, null,
            React.createElement("div", { className: "dark-mode" },
                React.createElement("header", { className: "masthead" },
                    React.createElement("nav", { id: "navigation", role: "navigation" },
                        React.createElement("div", { className: "navDesktop" },
                            React.createElement("section", { className: "nav__top" },
                                React.createElement("div", { className: "nav__wrapper nav__wrapper--top xs-col-11 xs-mx-auto" },
                                    React.createElement("ul", { className: "nav__logoWrapper list-unstyled" },
                                        React.createElement("li", null,
                                            React.createElement("a", { href: "/", className: "nav__logo" },
                                                React.createElement("img", { src: "https://cdna.pcpartpicker.com/static/forever/img/pcpp-logo.svg", className: "nav__logo--full" })))),
                                    React.createElement("ul", { className: "nav__account nav__account--desktop list-unstyled" },
                                        React.createElement("li", { className: "nav__account--login" },
                                            React.createElement("a", { href: "/accounts/login/" }, "Log In")),
                                        React.createElement("li", { className: "nav__account--register" },
                                            React.createElement("a", { href: "/accounts/register/", id: "js-trigger--profileMobile" }, "Register")),
                                        React.createElement("li", { className: "nav__account--country" },
                                            React.createElement("select", { className: "select select--small language-selector pp-country-select", name: "cc" },
                                                React.createElement("option", { value: "ar" }, "Argentina"),
                                                React.createElement("option", { value: "au" }, "Australia"),
                                                React.createElement("option", { value: "bh" }, "Bahrain"),
                                                React.createElement("option", { value: "be" }, "Belgium"),
                                                React.createElement("option", { value: "br" }, "Brazil"),
                                                React.createElement("option", { value: "ca" }, "Canada"),
                                                React.createElement("option", { value: "dk" }, "Denmark"),
                                                React.createElement("option", { value: "fi" }, "Finland"),
                                                React.createElement("option", { value: "fr" }, "France"),
                                                React.createElement("option", { value: "de" }, "Germany"),
                                                React.createElement("option", { value: "hk" }, "Hong Kong"),
                                                React.createElement("option", { value: "in" }, "India"),
                                                React.createElement("option", { value: "ie" }, "Ireland"),
                                                React.createElement("option", { value: "il" }, "Israel"),
                                                React.createElement("option", { value: "it" }, "Italy"),
                                                React.createElement("option", { value: "jp" }, "Japan"),
                                                React.createElement("option", { value: "kw" }, "Kuwait"),
                                                React.createElement("option", { value: "mx" }, "Mexico"),
                                                React.createElement("option", { value: "nl" }, "Netherlands"),
                                                React.createElement("option", { value: "nz" }, "New Zealand"),
                                                React.createElement("option", { value: "no" }, "Norway"),
                                                React.createElement("option", { value: "om" }, "Oman"),
                                                React.createElement("option", { value: "ph" }, "Philippines"),
                                                React.createElement("option", { value: "pl" }, "Poland"),
                                                React.createElement("option", { value: "pt" }, "Portugal"),
                                                React.createElement("option", { value: "qa" }, "Qatar"),
                                                React.createElement("option", { value: "ro" }, "Romania"),
                                                React.createElement("option", { value: "sa" }, "Saudi Arabia"),
                                                React.createElement("option", { value: "sg" }, "Singapore"),
                                                React.createElement("option", { value: "kr" }, "South Korea"),
                                                React.createElement("option", { value: "es" }, "Spain"),
                                                React.createElement("option", { value: "se" }, "Sweden"),
                                                React.createElement("option", { value: "th" }, "Thailand"),
                                                React.createElement("option", { value: "tr" }, "Turkey"),
                                                React.createElement("option", { value: "ae" }, "United Arab Emirates"),
                                                React.createElement("option", { value: "uk" }, "United Kingdom"),
                                                React.createElement("option", { value: "us" }, "United States")),
                                            React.createElement("span", { className: "flag-icon flag-us" })),
                                        React.createElement("li", { className: "nav__account--mode" },
                                            React.createElement("p", { className: "modeSwitch__label" }, "Light Mode"),
                                            React.createElement("div", { className: "modeSwitch" },
                                                React.createElement("div", { className: "modeSwitch__wrapper pp_toggle_theme" },
                                                    React.createElement("div", { className: "modeSwitch__toggle modeSwitch__toggle--dark-mode" }))))))),
                            React.createElement("section", { className: "nav__bottom" },
                                React.createElement("div", { className: "nav__wrapper nav__wrapper--bottom xs-col-11 xs-mx-auto" },
                                    React.createElement("ul", { className: "nav__categories list-unstyled" },
                                        React.createElement("li", { className: "nav__categories--partlist" },
                                            React.createElement("a", { href: "/list/" },
                                                React.createElement("svg", { className: "nav__icon", xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 24 24" },
                                                    React.createElement("g", { "data-name": "Layer 2" },
                                                        React.createElement("path", { d: "M23.85 7.87a6.39 6.39 0 0 1-1.79 3.31 6.54 6.54 0 0 1-6.93 1.5L4.58 23.22a2.57 2.57 0 0 1-1.89.78 2.64 2.64 0 0 1-1.91-.78 2.68 2.68 0 0 1-.78-1.9 2.71 2.71 0 0 1 .78-1.9L11.32 8.87a6.54 6.54 0 0 1 1.5-6.93A6.39 6.39 0 0 1 16.13.15a6.12 6.12 0 0 1 3.63.29l-4.1 4.1.4 3.4 3.4.4 4.1-4.1a6.12 6.12 0 0 1 .29 3.63z", "data-name": "Layer 1" }))),
                                                "System Builder")),
                                        React.createElement("li", { className: "nav__categories--guides" },
                                            React.createElement("a", { href: "/guide/" },
                                                React.createElement("svg", { className: "nav__icon", xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 18 24" },
                                                    React.createElement("g", { "data-name": "Layer 2" },
                                                        React.createElement("path", { d: "M12 0H0v24h18V6zm4 22H2v-2h3v-1H2v-2h5v-1H2v-2h3v-1H2v-2h5v-1H2V8h3V7H2V5h5V4H2V2h9v5h5z", "data-name": "Layer 1" }))),
                                                "Build Guides")),
                                        React.createElement("li", { className: "nav__categories--builds" },
                                            React.createElement("a", { href: "/builds/" },
                                                React.createElement("svg", { className: "nav__icon", xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 20 24" },
                                                    React.createElement("g", { "data-name": "Layer 2" },
                                                        React.createElement("g", { "data-name": "Layer 1" },
                                                            React.createElement("path", { d: "M19.08 1l-12-1H7a.62.62 0 0 0-.19 0h-.14l-.09.1-.13.07-.13.09L.45 4.17A1 1 0 0 0 0 5v17a1 1 0 0 0 .84 1l6 1H19a1 1 0 0 0 1-1V2a1 1 0 0 0-.92-1zM6 21.82l-4-.67V5.54l4-2.67zM18 22H8V2.09l10 .83z" }),
                                                            React.createElement("circle", { cx: 13, cy: 18, r: 1 }),
                                                            React.createElement("path", { d: "M17 4.6L9 4v2l8 .6v-2zM17 7.6L9 7v2l8 .6v-2z" })))),
                                                "Completed Builds")),
                                        React.createElement("li", { className: "nav__categories--browseProducts js-trigger--browseProducts" },
                                            React.createElement("a", { href: "#", className: "" },
                                                React.createElement("svg", { className: "nav__icon", xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 24 24" },
                                                    React.createElement("g", { "data-name": "Layer 2" },
                                                        React.createElement("g", { "data-name": "Layer 1" },
                                                            React.createElement("path", { d: "M8 8h8v8H8z" }),
                                                            React.createElement("path", { d: "M24 9V7h-2V4a2 2 0 0 0-2-2h-3V0h-2v2h-2V0h-2v2H9V0H7v2H4a2 2 0 0 0-2 2v3H0v2h2v2H0v2h2v2H0v2h2v3a2 2 0 0 0 2 2h3v2h2v-2h2v2h2v-2h2v2h2v-2h3a2 2 0 0 0 2-2v-3h2v-2h-2v-2h2v-2h-2V9zm-4 11H4V4h16z" })))),
                                                "Browse Products",
                                                React.createElement("span", { className: "down-caret" },
                                                    React.createElement("svg", { className: "icon shape-dropdown-arrow" },
                                                        React.createElement("use", { xlinkHref: "#shape-dropdown-arrow" }))))),
                                        React.createElement("li", { className: "nav__subLinks" },
                                            React.createElement("div", { className: "nav__subLinks--group1" },
                                                React.createElement("a", { href: "/products/pricedrop/", className: "nav__categories--drops" }, "Price Drops"),
                                                React.createElement("a", { href: "/forums/", className: "nav__categories--forums" }, "Forums")),
                                            React.createElement("div", { className: "nav__subLinks--group2" },
                                                React.createElement("a", { href: "/trends/", className: "nav__categories--trends" }, "Price Trends"),
                                                React.createElement("a", { href: "/blog/", className: "nav__categories--blog" }, "Blog"))),
                                        React.createElement("li", null,
                                            React.createElement("div", { className: "browseProducts browseProducts--hide" },
                                                React.createElement("div", { className: "browseProducts__wrapper xs-col-11 xs-mx-auto" },
                                                    React.createElement("div", { className: "browseProducts__block--group1" },
                                                        React.createElement("ul", { className: "browseProducts__block--popular list-unstyled" },
                                                            React.createElement("li", null,
                                                                React.createElement("a", { href: "/products/cpu/" },
                                                                    React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-cpu.png", alt: "CPU" }),
                                                                    "CPU")),
                                                            React.createElement("li", null,
                                                                React.createElement("a", { href: "/products/cpu-cooler/" },
                                                                    React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-cpucooler.png", alt: "CPU Cooler" }),
                                                                    "CPU Cooler")),
                                                            React.createElement("li", null,
                                                                React.createElement("a", { href: "/products/motherboard/" },
                                                                    React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-motherboard.png", alt: "Motherboard" }),
                                                                    "Motherboard")),
                                                            React.createElement("li", null,
                                                                React.createElement("a", { href: "/products/memory/" },
                                                                    React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-memory.png", alt: "Memory" }),
                                                                    "Memory")),
                                                            React.createElement("li", null,
                                                                React.createElement("a", { href: "/products/internal-hard-drive/" },
                                                                    React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-ssd.png", alt: "Storage" }),
                                                                    "Storage")),
                                                            React.createElement("li", null,
                                                                React.createElement("a", { href: "/products/video-card/" },
                                                                    React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-videocard.png", alt: "Video Card" }),
                                                                    "Video Card")),
                                                            React.createElement("li", null,
                                                                React.createElement("a", { href: "/products/power-supply/" },
                                                                    React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-powersupply.png", alt: "Power Supply" }),
                                                                    "Power Supply")),
                                                            React.createElement("li", null,
                                                                React.createElement("a", { href: "/products/case/" },
                                                                    React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-case.png", alt: "Case" }),
                                                                    "Case")))),
                                                    React.createElement("div", { className: "browseProducts__block--group2" },
                                                        React.createElement("div", { className: "browseProducts__col1" },
                                                            React.createElement("ul", { className: "browseProducts__block--cooling list-unstyled" },
                                                                React.createElement("li", null,
                                                                    React.createElement("h2", null, "Cooling")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/case-fan/" }, "Case Fans")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/fan-controller/" }, "Fan Controllers")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/thermal-paste/" }, "Thermal Compound"))),
                                                            React.createElement("ul", { className: "browseProducts__block--drives list-unstyled" },
                                                                React.createElement("li", null,
                                                                    React.createElement("h2", null, "Drives")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/optical-drive/" }, "Optical Drives"))),
                                                            React.createElement("ul", { className: "browseProducts__block--expansion list-unstyled" },
                                                                React.createElement("li", null,
                                                                    React.createElement("h2", null, "Expansion")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/sound-card/" }, "Sound Cards")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/wired-network-card/" }, "Wired Networking")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/wireless-network-card/" }, "Wireless Networking")))),
                                                        React.createElement("div", { className: "browseProducts__col2" },
                                                            React.createElement("ul", { className: "browseProducts__block--displays list-unstyled" },
                                                                React.createElement("li", null,
                                                                    React.createElement("h2", null, "Displays")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/monitor/" }, "Monitors"))),
                                                            React.createElement("ul", { className: "browseProducts__block--externalStorage list-unstyled" },
                                                                React.createElement("li", null,
                                                                    React.createElement("h2", null, "External Storage")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/external-hard-drive/" }, "External Hard Drives"))),
                                                            React.createElement("ul", { className: "browseProducts__block--peripherals list-unstyled" },
                                                                React.createElement("li", null,
                                                                    React.createElement("h2", null, "Peripherals")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/headphones/" }, "Headphones")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/keyboard/" }, "Keyboards")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/mouse/" }, "Mice")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/speakers/" }, "Speakers")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/ups/" }, "Uninterruptible Power Supplies")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/webcam/" }, "Webcams")))),
                                                        React.createElement("div", { className: "browseProducts__col3" },
                                                            React.createElement("ul", { className: "browseProducts__block--software list-unstyled" },
                                                                React.createElement("li", null,
                                                                    React.createElement("h2", null, "Software")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/software/#W=1" }, "Antivirus")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/software/#W=8" }, "Audio & Video")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/software/#W=2" }, "Backup")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/software/#W=3" }, "Design & Illustration")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/software/#W=5" }, "Internet Security")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/software/#W=7" }, "Office & Productivity")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/os/" }, "Operating Systems")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/software/#W=6" }, "Photography"))),
                                                            React.createElement("ul", { className: "browseProducts__block--software list-unstyled" },
                                                                React.createElement("li", null,
                                                                    React.createElement("h2", null, "Other")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "/products/laptop/" }, "Laptops"))))))))),
                                    React.createElement("a", { className: "nav__search js-trigger-offCanvas--search", href: "#" },
                                        React.createElement("svg", { className: "icon shape-search" },
                                            React.createElement("use", { xlinkHref: "#shape-search" })))))),
                        React.createElement("div", { className: "navMobile xs-py1 xs-px2" },
                            React.createElement("div", { className: "nav__wrapper" },
                                React.createElement("ul", { className: "nav__logoWrapper list-unstyled" },
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "#", className: "nav__back" },
                                            React.createElement("svg", { className: "icon shape-dropdown-arrow" },
                                                React.createElement("use", { xlinkHref: "#shape-dropdown-arrow" })))),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "/", className: "nav__logo" },
                                            React.createElement("img", { src: "/static/img/pcpp-icon.svg", className: "nav__logo--icon" })))),
                                React.createElement("ul", { className: "nav__menu--mobile list-unstyled" },
                                    React.createElement("li", { className: "nav-icon nav-icon--builder" },
                                        React.createElement("a", { className: "", href: "/list" },
                                            React.createElement("svg", { className: "icon shape-wrench" },
                                                React.createElement("use", { xlinkHref: "#shape-wrench" })))),
                                    React.createElement("li", { className: "nav-icon nav-icon--parts js-trigger--browseProducts" },
                                        React.createElement("a", { className: "", href: "#" },
                                            React.createElement("svg", { className: "icon shape-cpu" },
                                                React.createElement("use", { xlinkHref: "#shape-cpu" })))),
                                    React.createElement("li", { className: "nav-icon nav-icon--search" },
                                        React.createElement("a", { className: "js-trigger-offCanvas--search", href: "#" },
                                            React.createElement("svg", { className: "icon shape-search" },
                                                React.createElement("use", { xlinkHref: "#shape-search" })))),
                                    React.createElement("li", { className: "nav-divider" }),
                                    React.createElement("li", { className: "nav-icon nav-icon--account" },
                                        React.createElement("a", { href: "#", className: "js-trigger--accountMobile" },
                                            React.createElement("svg", { className: "icon shape-user" },
                                                React.createElement("use", { xlinkHref: "#shape-user" })))),
                                    React.createElement("li", { className: "nav-icon nav-icon--resources" },
                                        React.createElement("a", { href: "#", className: "js-trigger--resourcesMobile" },
                                            React.createElement("svg", { className: "icon shape-menu" },
                                                React.createElement("use", { xlinkHref: "#shape-menu" }))))))),
                        React.createElement("div", { className: "navCard navCard--search" },
                            React.createElement("div", { className: "navCard__header" },
                                React.createElement("div", { className: "navCard__wrapper" },
                                    React.createElement("a", { href: "#", className: "nav__back js-trigger--close" },
                                        React.createElement("svg", { className: "icon shape-dropdown-arrow" },
                                            React.createElement("use", { xlinkHref: "#shape-dropdown-arrow" }))),
                                    React.createElement("h6", { className: "navCard__title" },
                                        React.createElement("svg", { className: "icon shape-search" },
                                            React.createElement("use", { xlinkHref: "#shape-search" })),
                                        React.createElement("span", null, "Search Products")))),
                            React.createElement("div", { className: "navCard__content" },
                                React.createElement("div", { className: "md-col-11 xs-mx-auto xs-py3 xs-px2 md-px0" },
                                    React.createElement("div", { className: "searchField" },
                                        React.createElement("form", { id: "site_search_nav", action: "/search/", method: "get" },
                                            React.createElement("input", { id: "search_q", name: "q", type: "text", className: "text-input inactive_search", placeholder: "Search..." }),
                                            React.createElement("button", { className: "button button--primary xs-col-12" /*onclick="$('#site_search_nav').submit();return false;"*/ }, "Search"))),
                                    React.createElement("div", { className: "navSearch__content" },
                                        React.createElement("div", { className: "navSearch__wrapper" },
                                            React.createElement("section", { className: "", id: "search_result" },
                                                React.createElement("div", { className: "search_results" }))))))),
                        React.createElement("div", { className: "navCard navCard--products" },
                            React.createElement("div", { className: "navCard__header" },
                                React.createElement("div", { className: "navCard__wrapper" },
                                    React.createElement("a", { href: "#", className: "nav__back js-trigger--close" },
                                        React.createElement("svg", { className: "icon shape-dropdown-arrow" },
                                            React.createElement("use", { xlinkHref: "#shape-dropdown-arrow" }))),
                                    React.createElement("h6", { className: "navCard__title" },
                                        React.createElement("svg", { className: "icon shape-cpu" },
                                            React.createElement("use", { xlinkHref: "#shape-cpu" })),
                                        React.createElement("span", null, "Browse Products")))),
                            React.createElement("div", { className: "navCard__content" },
                                React.createElement("div", { className: "navCard__wrapper" },
                                    React.createElement("div", { className: "browseProducts browseProducts--hide" },
                                        React.createElement("div", { className: "browseProducts__block--group1" },
                                            React.createElement("ul", { className: "browseProducts__block--popular list-unstyled" },
                                                React.createElement("li", null,
                                                    React.createElement("a", { href: "/products/cpu/" },
                                                        React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-cpu.png", alt: "CPU" }),
                                                        "CPU")),
                                                React.createElement("li", null,
                                                    React.createElement("a", { href: "/products/cpu-cooler/" },
                                                        React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-cpucooler.png", alt: "CPU Cooler" }),
                                                        "CPU Cooler")),
                                                React.createElement("li", null,
                                                    React.createElement("a", { href: "/products/motherboard/" },
                                                        React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-motherboard.png", alt: "Motherboard" }),
                                                        "Motherboard")),
                                                React.createElement("li", null,
                                                    React.createElement("a", { href: "/products/memory/" },
                                                        React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-memory.png", alt: "Memory" }),
                                                        "Memory")),
                                                React.createElement("li", null,
                                                    React.createElement("a", { href: "/products/internal-hard-drive/" },
                                                        React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-ssd.png", alt: "Storage" }),
                                                        "Storage")),
                                                React.createElement("li", null,
                                                    React.createElement("a", { href: "/products/video-card/" },
                                                        React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-videocard.png", alt: "Video Card" }),
                                                        "Video Card")),
                                                React.createElement("li", null,
                                                    React.createElement("a", { href: "/products/power-supply/" },
                                                        React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-powersupply.png", alt: "Power Supply" }),
                                                        "Power Supply")),
                                                React.createElement("li", null,
                                                    React.createElement("a", { href: "/products/case/" },
                                                        React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/img/nav-case.png", alt: "Case" }),
                                                        "Case")))),
                                        React.createElement("div", { className: "browseProducts__block--group2" },
                                            React.createElement("div", { className: "browseProducts__col1" },
                                                React.createElement("ul", { className: "browseProducts__block--cooling list-unstyled" },
                                                    React.createElement("li", null,
                                                        React.createElement("h2", null, "Cooling")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/case-fan/" }, "Case Fans")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/fan-controller/" }, "Fan Controllers")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/thermal-paste/" }, "Thermal Compound"))),
                                                React.createElement("ul", { className: "browseProducts__block--drives list-unstyled" },
                                                    React.createElement("li", null,
                                                        React.createElement("h2", null, "Drives")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/optical-drive/" }, "Optical Drives"))),
                                                React.createElement("ul", { className: "browseProducts__block--expansion list-unstyled" },
                                                    React.createElement("li", null,
                                                        React.createElement("h2", null, "Expansion")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/sound-card/" }, "Sound Cards")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/wired-network-card/" }, "Wired Networking")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/wireless-network-card/" }, "Wireless Networking")))),
                                            React.createElement("div", { className: "browseProducts__col2" },
                                                React.createElement("ul", { className: "browseProducts__block--displays list-unstyled" },
                                                    React.createElement("li", null,
                                                        React.createElement("h2", null, "Displays")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/monitor/" }, "Monitors"))),
                                                React.createElement("ul", { className: "browseProducts__block--externalStorage list-unstyled" },
                                                    React.createElement("li", null,
                                                        React.createElement("h2", null, "External Storage")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/external-hard-drive/" }, "External Hard Drives"))),
                                                React.createElement("ul", { className: "browseProducts__block--peripherals list-unstyled" },
                                                    React.createElement("li", null,
                                                        React.createElement("h2", null, "Peripherals")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/headphones/" }, "Headphones")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/keyboard/" }, "Keyboards")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/mouse/" }, "Mice")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/speakers/" }, "Speakers")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/ups/" }, "Uninterruptible Power Supplies")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/webcam/" }, "Webcams")))),
                                            React.createElement("div", { className: "browseProducts__col3" },
                                                React.createElement("ul", { className: "browseProducts__block--software list-unstyled" },
                                                    React.createElement("li", null,
                                                        React.createElement("h2", null, "Software")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/software/#W=1" }, "Antivirus")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/software/#W=8" }, "Audio & Video")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/software/#W=2" }, "Backup")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/software/#W=3" }, "Design & Illustration")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/software/#W=5" }, "Internet Security")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/software/#W=7" }, "Office & Productivity")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/os/" }, "Operating Systems")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/software/#W=6" }, "Photography"))),
                                                React.createElement("ul", { className: "browseProducts__block--software list-unstyled" },
                                                    React.createElement("li", null,
                                                        React.createElement("h2", null, "Other")),
                                                    React.createElement("li", null,
                                                        React.createElement("a", { href: "/products/laptop/" }, "Laptops"))))))))),
                        React.createElement("div", { className: "navCard navCard--account" },
                            React.createElement("div", { className: "navCard__header" },
                                React.createElement("div", { className: "navCard__wrapper" },
                                    React.createElement("a", { href: "#", className: "nav__back js-trigger--close" },
                                        React.createElement("svg", { className: "icon shape-dropdown-arrow" },
                                            React.createElement("use", { xlinkHref: "#shape-dropdown-arrow" }))),
                                    React.createElement("h6", { className: "navCard__title" },
                                        React.createElement("svg", { className: "icon shape-user" },
                                            React.createElement("use", { xlinkHref: "#shape-user" })),
                                        React.createElement("span", null, "Account")))),
                            React.createElement("div", { className: "navCard__content" },
                                React.createElement("div", { className: "navCard__wrapper" },
                                    React.createElement("ul", { className: "nav__account nav__account--mobile list-unstyled" },
                                        React.createElement("li", { className: "nav__account--country" },
                                            React.createElement("select", { className: "select select--small language-selector pp-country-select", name: "cc" },
                                                React.createElement("option", { value: "ar" }, "Argentina"),
                                                React.createElement("option", { value: "au" }, "Australia"),
                                                React.createElement("option", { value: "bh" }, "Bahrain"),
                                                React.createElement("option", { value: "be" }, "Belgium"),
                                                React.createElement("option", { value: "br" }, "Brazil"),
                                                React.createElement("option", { value: "ca" }, "Canada"),
                                                React.createElement("option", { value: "dk" }, "Denmark"),
                                                React.createElement("option", { value: "fi" }, "Finland"),
                                                React.createElement("option", { value: "fr" }, "France"),
                                                React.createElement("option", { value: "de" }, "Germany"),
                                                React.createElement("option", { value: "hk" }, "Hong Kong"),
                                                React.createElement("option", { value: "in" }, "India"),
                                                React.createElement("option", { value: "ie" }, "Ireland"),
                                                React.createElement("option", { value: "il" }, "Israel"),
                                                React.createElement("option", { value: "it" }, "Italy"),
                                                React.createElement("option", { value: "jp" }, "Japan"),
                                                React.createElement("option", { value: "kw" }, "Kuwait"),
                                                React.createElement("option", { value: "mx" }, "Mexico"),
                                                React.createElement("option", { value: "nl" }, "Netherlands"),
                                                React.createElement("option", { value: "nz" }, "New Zealand"),
                                                React.createElement("option", { value: "no" }, "Norway"),
                                                React.createElement("option", { value: "om" }, "Oman"),
                                                React.createElement("option", { value: "ph" }, "Philippines"),
                                                React.createElement("option", { value: "pl" }, "Poland"),
                                                React.createElement("option", { value: "pt" }, "Portugal"),
                                                React.createElement("option", { value: "qa" }, "Qatar"),
                                                React.createElement("option", { value: "ro" }, "Romania"),
                                                React.createElement("option", { value: "sa" }, "Saudi Arabia"),
                                                React.createElement("option", { value: "sg" }, "Singapore"),
                                                React.createElement("option", { value: "kr" }, "South Korea"),
                                                React.createElement("option", { value: "es" }, "Spain"),
                                                React.createElement("option", { value: "se" }, "Sweden"),
                                                React.createElement("option", { value: "th" }, "Thailand"),
                                                React.createElement("option", { value: "tr" }, "Turkey"),
                                                React.createElement("option", { value: "ae" }, "United Arab Emirates"),
                                                React.createElement("option", { value: "uk" }, "United Kingdom"),
                                                React.createElement("option", { value: "us" }, "United States")),
                                            React.createElement("span", { className: "flag-icon flag-us" })),
                                        React.createElement("li", { className: "nav__account--mode" },
                                            React.createElement("p", { className: "modeSwitch__label" }, "Light Mode"),
                                            React.createElement("div", { className: "modeSwitch" },
                                                React.createElement("div", { className: "modeSwitch__wrapper pp_toggle_theme" },
                                                    React.createElement("div", { className: "modeSwitch__toggle modeSwitch__toggle--dark-mode" })))),
                                        React.createElement("li", { className: "nav__account--login" },
                                            React.createElement("a", { href: "/accounts/login/" }, "Log In")),
                                        React.createElement("li", { className: "nav__account--register" },
                                            React.createElement("a", { href: "/accounts/register/", id: "js-trigger--profileMobile" }, "Register")))))),
                        React.createElement("div", { className: "navCard navCard--resources" },
                            React.createElement("div", { className: "navCard__header" },
                                React.createElement("div", { className: "navCard__wrapper" },
                                    React.createElement("a", { href: "#", className: "nav__back js-trigger--close" },
                                        React.createElement("svg", { className: "icon shape-dropdown-arrow" },
                                            React.createElement("use", { xlinkHref: "#shape-dropdown-arrow" }))),
                                    React.createElement("h6", { className: "navCard__title" },
                                        React.createElement("svg", { className: "icon shape-menu" },
                                            React.createElement("use", { xlinkHref: "#shape-menu" })),
                                        React.createElement("span", null, "Resources")))),
                            React.createElement("div", { className: "navCard__content" },
                                React.createElement("div", { className: "navCard__wrapper" },
                                    React.createElement("ul", { className: "list-unstyled" },
                                        React.createElement("li", { className: "nav__categories--guides" },
                                            React.createElement("a", { href: "/guide/" },
                                                React.createElement("svg", { className: "nav__icon", xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 18 24" },
                                                    React.createElement("g", { "data-name": "Layer 2" },
                                                        React.createElement("path", { d: "M12 0H0v24h18V6zm4 22H2v-2h3v-1H2v-2h5v-1H2v-2h3v-1H2v-2h5v-1H2V8h3V7H2V5h5V4H2V2h9v5h5z", "data-name": "Layer 1" }))),
                                                "Build Guides")),
                                        React.createElement("li", { className: "nav__categories--builds" },
                                            React.createElement("a", { href: "/builds/" },
                                                React.createElement("svg", { className: "nav__icon", xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 20 24" },
                                                    React.createElement("g", { "data-name": "Layer 2" },
                                                        React.createElement("g", { "data-name": "Layer 1" },
                                                            React.createElement("path", { d: "M19.08 1l-12-1H7a.62.62 0 0 0-.19 0h-.14l-.09.1-.13.07-.13.09L.45 4.17A1 1 0 0 0 0 5v17a1 1 0 0 0 .84 1l6 1H19a1 1 0 0 0 1-1V2a1 1 0 0 0-.92-1zM6 21.82l-4-.67V5.54l4-2.67zM18 22H8V2.09l10 .83z" }),
                                                            React.createElement("circle", { cx: 13, cy: 18, r: 1 }),
                                                            React.createElement("path", { d: "M17 4.6L9 4v2l8 .6v-2zM17 7.6L9 7v2l8 .6v-2z" })))),
                                                "Completed Builds")),
                                        React.createElement("li", { className: "nav__categories--drops" },
                                            React.createElement("a", { href: "/products/pricedrop/" }, "Price Drops")),
                                        React.createElement("li", { className: "nav__categories--forums" },
                                            React.createElement("a", { href: "/forums/" }, "Forums")),
                                        React.createElement("li", { className: "nav__categories--trends" },
                                            React.createElement("a", { href: "/trends/" }, "Price Trends")),
                                        React.createElement("li", { className: "nav__categories--blog" },
                                            React.createElement("a", { href: "/blog/" }, "Blog")))))))),
                React.createElement("section", { className: "main-wrapper xs-col-12" },
                    React.createElement("div", { id: "homepage" },
                        React.createElement("div", { className: "wrapper wrapper__buildGuides" },
                            React.createElement("section", { className: "build-guides xs-col-11 lg-col-9 xl-col-8 xs-mx-auto" },
                                React.createElement("div", { className: "guides__info" },
                                    React.createElement("h1", null, "Build Guides"),
                                    React.createElement("p", null, "Building your own PC and need ideas on where to get started? Explore our build guides which cover systems for a variety of use-cases and budgets."),
                                    React.createElement("a", { href: "/guide/", className: "button" }, "View the Build Guides")),
                                React.createElement("li", { className: "guideGroup guideGroup__card" },
                                    React.createElement("a", { href: "/guide/PB6MnQ/entry-level-amd-gaming-build", className: "guideGroup__target" }),
                                    React.createElement("div", { className: "guideGroup__content--wrapper1" },
                                        React.createElement("h1", { className: "guide__title" }, "Entry Level AMD Gaming Build"),
                                        React.createElement("ul", { className: "guide__keyProducts list-unstyled" },
                                            React.createElement("li", null, "AMD Ryzen 5 2600"),
                                            React.createElement("li", null, "Parametric Video Card (Chipset: GeForce GTX 1650 SUPER)"),
                                            React.createElement("li", null, "Cougar MX330 ATX Mid Tower"))),
                                    React.createElement("div", { className: "guideGroup__content--wrapper2" },
                                        React.createElement("div", { className: "guide__numbers" },
                                            React.createElement("p", { className: "guide__price" }, "$582.93"),
                                            React.createElement("p", { className: "guide__links" },
                                                React.createElement("span", { className: "guide__link--comments" },
                                                    React.createElement("svg", { className: "icon shape-comment" },
                                                        React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                    "189"))),
                                        React.createElement("ul", { className: "guide__images list-unstyled" },
                                            React.createElement("li", { className: "guide__images--1" },
                                                React.createElement("img", { src: "https://images-na.ssl-images-amazon.com/images/I/51N2BQA3cBL.jpg" })),
                                            React.createElement("li", { className: "guide__images--2" },
                                                React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/product/55aea2dd64e2e3a3e3b1d678048d8d76.256p.jpg" })),
                                            React.createElement("li", { className: "guide__images--3" },
                                                React.createElement("img", { src: "https://m.media-amazon.com/images/I/41zgLYpzn1L.jpg" }))))),
                                React.createElement("li", { className: "guideGroup guideGroup__card" },
                                    React.createElement("a", { href: "/guide/s4V323/excellent-intel-gamingstreaming-build", className: "guideGroup__target" }),
                                    React.createElement("div", { className: "guideGroup__content--wrapper1" },
                                        React.createElement("h1", { className: "guide__title" }, "Excellent Intel Gaming/Streaming Build"),
                                        React.createElement("ul", { className: "guide__keyProducts list-unstyled" },
                                            React.createElement("li", null, "Intel Core i5-10600K"),
                                            React.createElement("li", null, "Parametric Video Card (Chipset: GeForce RTX 3070)"),
                                            React.createElement("li", null, "Corsair 4000D Airflow ATX Mid Tower"))),
                                    React.createElement("div", { className: "guideGroup__content--wrapper2" },
                                        React.createElement("div", { className: "guide__numbers" },
                                            React.createElement("p", { className: "guide__price" }, "$1312.54"),
                                            React.createElement("p", { className: "guide__links" },
                                                React.createElement("span", { className: "guide__link--comments" },
                                                    React.createElement("svg", { className: "icon shape-comment" },
                                                        React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                    "63"))),
                                        React.createElement("ul", { className: "guide__images list-unstyled" },
                                            React.createElement("li", { className: "guide__images--1" },
                                                React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/product/bc6e987da3fe22c616898d1d7fa3d227.256p.jpg" })),
                                            React.createElement("li", { className: "guide__images--2" },
                                                React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/product/cec5ee818776737baefc9603bdbf9391.256p.jpg" })),
                                            React.createElement("li", { className: "guide__images--3" },
                                                React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/product/200b4e048d11f6870e697e2693490cd3.256p.jpg" }))))))),
                        React.createElement("div", { className: "wrapper wrapper__completedBuilds" },
                            React.createElement("section", { className: "completed-builds xs-col-11 lg-col-9 xl-col-8 xs-mx-auto" },
                                React.createElement("section", { className: "module-subTitle" },
                                    React.createElement("div", { className: "subTitle" },
                                        React.createElement("div", { className: "subTitle__header" },
                                            React.createElement("h2", null, "Completed Builds")))),
                                React.createElement("ul", { id: "userbuild_list", className: "logGrid list-unstyled" },
                                    React.createElement("li", { className: "logGroup__card--featured" },
                                        React.createElement("div", { className: "featured__message" },
                                            React.createElement("p", null,
                                                React.createElement("svg", { className: "nav__icon", xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 20 24" },
                                                    React.createElement("g", { "data-name": "Layer 2" },
                                                        React.createElement("g", { "data-name": "Layer 1" },
                                                            React.createElement("path", { d: "M19.08 1l-12-1H7a.62.62 0 0 0-.19 0h-.14l-.09.1-.13.07-.13.09L.45 4.17A1 1 0 0 0 0 5v17a1 1 0 0 0 .84 1l6 1H19a1 1 0 0 0 1-1V2a1 1 0 0 0-.92-1zM6 21.82l-4-.67V5.54l4-2.67zM18 22H8V2.09l10 .83z" }),
                                                            React.createElement("circle", { cx: 13, cy: 18, r: 1 }),
                                                            React.createElement("path", { d: "M17 4.6L9 4v2l8 .6v-2zM17 7.6L9 7v2l8 .6v-2z" }))))),
                                            React.createElement("h1", null, "Featured Build"),
                                            React.createElement("p", null,
                                                "Congratulations ",
                                                React.createElement("a", { href: "/user/_Rip_/" }, "_Rip_"),
                                                "!")),
                                        React.createElement("div", { className: "logGroup logGroup__card" },
                                            React.createElement("a", { href: "/b/72BZxr", className: "logGroup__target" }),
                                            React.createElement("div", { className: "logGroup__content--wrapper1" },
                                                React.createElement("p", { className: "log__author" },
                                                    React.createElement("a", { href: "/user/_Rip_/", className: "userAvatar" },
                                                        React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/user/3845343.42e1e783996dc1669c451b48858a5481.256c.jpg" })),
                                                    React.createElement("a", { href: "/user/_Rip_/" }, "_Rip_")),
                                                React.createElement("a", { href: "/b/72BZxr", className: "log__image", style: { backgroundImage: 'url(//cdna.pcpartpicker.com/static/forever/images/userbuild/331461.a4ad9c81e55c97936fc399a8725566f0.512.jpg)' } }),
                                                React.createElement("h1", { className: "log__title" },
                                                    React.createElement("a", { href: "/b/72BZxr" }, "Master Build - Corsair Obsidian 1000d")),
                                                React.createElement("ul", { className: "log__keyProducts list-unstyled" },
                                                    React.createElement("li", { className: "build__specs" }, "AMD Threadripper 3960X"),
                                                    React.createElement("li", { className: "build__specs" }, "GeForce RTX 2080 Ti (x2)"))),
                                            React.createElement("div", { className: "logGroup__content--wrapper2" },
                                                React.createElement("div", { className: "log__numbers" },
                                                    React.createElement("p", { className: "log__price" }, "$19405.89+"),
                                                    React.createElement("p", { className: "log__links" },
                                                        React.createElement("span", { className: "log__link--followers" },
                                                            React.createElement("svg", { className: "icon shape-arrow-up" },
                                                                React.createElement("use", { xlinkHref: "#shape-arrow-up" })),
                                                            "259"),
                                                        React.createElement("span", { className: "log__link--comments" },
                                                            React.createElement("svg", { className: "icon shape-comment" },
                                                                React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                            "248")))))),
                                    React.createElement("li", { className: "logGroup logGroup__card" },
                                        React.createElement("a", { href: "/b/yRMcCJ", className: "logGroup__target" }),
                                        React.createElement("div", { className: "logGroup__content--wrapper1" },
                                            React.createElement("p", { className: "log__author" },
                                                React.createElement("a", { href: "/user/Soldr/", className: "userAvatar" },
                                                    React.createElement("img", { src: "/static/img/default-avatar.png" })),
                                                React.createElement("a", { href: "/user/Soldr/" }, "Soldr")),
                                            React.createElement("a", { href: "/b/yRMcCJ", className: "log__image", style: { backgroundImage: 'url(//cdna.pcpartpicker.com/static/forever/images/userbuild/334874.eee74d879b0b0054c6aacda77ba91c03.512.jpg)' } }),
                                            React.createElement("h1", { className: "log__title" },
                                                React.createElement("a", { href: "/b/yRMcCJ" }, "My best build yet")),
                                            React.createElement("ul", { className: "log__keyProducts list-unstyled" },
                                                React.createElement("li", { className: "build__specs" }, "AMD Ryzen 7 3700X"),
                                                React.createElement("li", { className: "build__specs" }, "Radeon RX 580"))),
                                        React.createElement("div", { className: "logGroup__content--wrapper2" },
                                            React.createElement("div", { className: "log__numbers" },
                                                React.createElement("p", { className: "log__price" }, "$821.93+"),
                                                React.createElement("p", { className: "log__links" },
                                                    React.createElement("span", { className: "log__link--followers" },
                                                        React.createElement("svg", { className: "icon shape-arrow-up" },
                                                            React.createElement("use", { xlinkHref: "#shape-arrow-up" })),
                                                        "5"),
                                                    React.createElement("span", { className: "log__link--comments" },
                                                        React.createElement("svg", { className: "icon shape-comment" },
                                                            React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                        "3"))))),
                                    React.createElement("li", { className: "logGroup logGroup__card" },
                                        React.createElement("a", { href: "/b/nFp8TW", className: "logGroup__target" }),
                                        React.createElement("div", { className: "logGroup__content--wrapper1" },
                                            React.createElement("p", { className: "log__author" },
                                                React.createElement("a", { href: "/user/GaronAgrawal/", className: "userAvatar" },
                                                    React.createElement("img", { src: "/static/img/default-avatar.png" })),
                                                React.createElement("a", { href: "/user/GaronAgrawal/" }, "GaronAgrawal")),
                                            React.createElement("a", { href: "/b/nFp8TW", className: "log__image", style: { backgroundImage: 'url(//cdna.pcpartpicker.com/static/forever/images/userbuild/334864.83b5210a4855a7a4b40f581d9a8b8327.512.jpg)' } }),
                                            React.createElement("h1", { className: "log__title" },
                                                React.createElement("a", { href: "/b/nFp8TW" }, "First Build")),
                                            React.createElement("ul", { className: "log__keyProducts list-unstyled" },
                                                React.createElement("li", { className: "build__specs" }, "AMD Ryzen 5 3600XT"),
                                                React.createElement("li", { className: "build__specs" }, "GeForce RTX 2060"))),
                                        React.createElement("div", { className: "logGroup__content--wrapper2" },
                                            React.createElement("div", { className: "log__numbers" },
                                                React.createElement("p", { className: "log__price" }, "$1279.27+"),
                                                React.createElement("p", { className: "log__links" },
                                                    React.createElement("span", { className: "log__link--followers" },
                                                        React.createElement("svg", { className: "icon shape-arrow-up" },
                                                            React.createElement("use", { xlinkHref: "#shape-arrow-up" })),
                                                        "4"),
                                                    React.createElement("span", { className: "log__link--comments" },
                                                        React.createElement("svg", { className: "icon shape-comment" },
                                                            React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                        "6"))))),
                                    React.createElement("li", { className: "logGroup logGroup__card" },
                                        React.createElement("a", { href: "/b/jKx6Mp", className: "logGroup__target" }),
                                        React.createElement("div", { className: "logGroup__content--wrapper1" },
                                            React.createElement("p", { className: "log__author" },
                                                React.createElement("a", { href: "/user/Crazydamias7/", className: "userAvatar" },
                                                    React.createElement("img", { src: "/static/img/default-avatar.png" })),
                                                React.createElement("a", { href: "/user/Crazydamias7/" }, "Crazydamias7")),
                                            React.createElement("a", { href: "/b/jKx6Mp", className: "log__image", style: { backgroundImage: 'url(//cdna.pcpartpicker.com/static/forever/images/userbuild/334856.5e7af080067b80c178babe8c1c5c04b2.512.jpg)' } }),
                                            React.createElement("h1", { className: "log__title" },
                                                React.createElement("a", { href: "/b/jKx6Mp" }, "My Gaming PC")),
                                            React.createElement("ul", { className: "log__keyProducts list-unstyled" },
                                                React.createElement("li", { className: "build__specs" }, "Intel Core i5-7400"),
                                                React.createElement("li", { className: "build__specs" }, "GeForce GTX 1050 Ti"))),
                                        React.createElement("div", { className: "logGroup__content--wrapper2" },
                                            React.createElement("div", { className: "log__numbers" },
                                                React.createElement("p", { className: "log__price" }, "$1133.88+"),
                                                React.createElement("p", { className: "log__links" },
                                                    React.createElement("span", { className: "log__link--followers" },
                                                        React.createElement("svg", { className: "icon shape-arrow-up" },
                                                            React.createElement("use", { xlinkHref: "#shape-arrow-up" })),
                                                        "4"),
                                                    React.createElement("span", { className: "log__link--comments" },
                                                        React.createElement("svg", { className: "icon shape-comment" },
                                                            React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                        "3"))))),
                                    React.createElement("li", { className: "logGroup logGroup__card" },
                                        React.createElement("a", { href: "/b/6jskcf", className: "logGroup__target" }),
                                        React.createElement("div", { className: "logGroup__content--wrapper1" },
                                            React.createElement("p", { className: "log__author" },
                                                React.createElement("a", { href: "/user/NasTomkinson/", className: "userAvatar" },
                                                    React.createElement("img", { src: "/static/img/default-avatar.png" })),
                                                React.createElement("a", { href: "/user/NasTomkinson/" }, "NasTomkinson")),
                                            React.createElement("a", { href: "/b/6jskcf", className: "log__image", style: { backgroundImage: 'url(//cdna.pcpartpicker.com/static/forever/images/userbuild/334855.2c2a42468645676fc90e755996fd237f.512.jpg)' } }),
                                            React.createElement("h1", { className: "log__title" },
                                                React.createElement("a", { href: "/b/6jskcf" }, "5800X + 6800XT Red Team build")),
                                            React.createElement("ul", { className: "log__keyProducts list-unstyled" },
                                                React.createElement("li", { className: "build__specs" }, "AMD Ryzen 7 5800X"),
                                                React.createElement("li", { className: "build__specs" }, "Radeon RX 6800 XT"))),
                                        React.createElement("div", { className: "logGroup__content--wrapper2" },
                                            React.createElement("div", { className: "log__numbers" },
                                                React.createElement("p", { className: "log__price" }, "$1008.39+"),
                                                React.createElement("p", { className: "log__links" },
                                                    React.createElement("span", { className: "log__link--followers" },
                                                        React.createElement("svg", { className: "icon shape-arrow-up" },
                                                            React.createElement("use", { xlinkHref: "#shape-arrow-up" })),
                                                        "11"),
                                                    React.createElement("span", { className: "log__link--comments" },
                                                        React.createElement("svg", { className: "icon shape-comment" },
                                                            React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                        "6"))))),
                                    React.createElement("li", { className: "logGroup logGroup__card" },
                                        React.createElement("a", { href: "/b/rhdmP6", className: "logGroup__target" }),
                                        React.createElement("div", { className: "logGroup__content--wrapper1" },
                                            React.createElement("p", { className: "log__author" },
                                                React.createElement("a", { href: "/user/czvczx/", className: "userAvatar" },
                                                    React.createElement("img", { src: "/static/img/default-avatar.png" })),
                                                React.createElement("a", { href: "/user/czvczx/" }, "czvczx")),
                                            React.createElement("a", { href: "/b/rhdmP6", className: "log__image", style: { backgroundImage: 'url(//cdna.pcpartpicker.com/static/forever/images/userbuild/334851.bc573305605e292d84d855144d1d14e1.512.jpg)' } }),
                                            React.createElement("h1", { className: "log__title" },
                                                React.createElement("a", { href: "/b/rhdmP6" }, "2020 build")),
                                            React.createElement("ul", { className: "log__keyProducts list-unstyled" },
                                                React.createElement("li", { className: "build__specs" }, "AMD Ryzen 9 5900X"),
                                                React.createElement("li", { className: "build__specs" }, "GeForce RTX 3080"))),
                                        React.createElement("div", { className: "logGroup__content--wrapper2" },
                                            React.createElement("div", { className: "log__numbers" },
                                                React.createElement("p", { className: "log__price" }, "$3756.47+"),
                                                React.createElement("p", { className: "log__links" },
                                                    React.createElement("span", { className: "log__link--followers" },
                                                        React.createElement("svg", { className: "icon shape-arrow-up" },
                                                            React.createElement("use", { xlinkHref: "#shape-arrow-up" })),
                                                        "6"),
                                                    React.createElement("span", { className: "log__link--comments" },
                                                        React.createElement("svg", { className: "icon shape-comment" },
                                                            React.createElement("use", { xlinkHref: "#shape-comment" })),
                                                        "7"))))),
                                    React.createElement("li", { className: "logGroup__action" },
                                        React.createElement("p", null,
                                            React.createElement("a", { href: "/builds/", className: "button" }, "See All Completed Builds")))))),
                        React.createElement("div", { className: "wrapper wrapper__blogPosts" },
                            React.createElement("section", { className: "blog-posts xs-col-11 lg-col-9 xl-col-8 xs-mx-auto" },
                                React.createElement("section", { className: "module-subTitle" },
                                    React.createElement("div", { className: "subTitle" },
                                        React.createElement("div", { className: "subTitle__header" },
                                            React.createElement("h2", null, "Blog")))),
                                React.createElement("ul", { className: "blogGrid list-unstyled" },
                                    React.createElement("li", { className: "blogGroup" },
                                        React.createElement("a", { href: "/blog/163/charity-water-completion-report-13-14-15", className: "blog__image" },
                                            React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/content/cefdf8c662bb641f1f699f08540f950b.800.450.jpg" }),
                                            React.createElement("h1", { className: "blog__title" }, "charity: water Completion Reports #13, #14, #15")),
                                        React.createElement("p", { className: "meta" },
                                            "Posted July 8, 2020 by ",
                                            React.createElement("a", { href: "/user/philip/" }, "philip")),
                                        React.createElement("p", null,
                                            "Three more ",
                                            React.createElement("a", { href: "https://charitywater.org" }, "charity: water"),
                                            " completions report arrived! Thanks to your support, we were able to fund 9 water projects in Uganda, Ethiopia, and Nepal."),
                                        React.createElement("a", { href: "/blog/163/charity-water-completion-report-13-14-15#comments", className: "blog__link--comments" },
                                            React.createElement("svg", { className: "icon shape-comment" },
                                                React.createElement("use", { xlinkHref: "#shape-comment" })),
                                            "14")),
                                    React.createElement("li", { className: "blogGroup" },
                                        React.createElement("a", { href: "/blog/162/charity-water-completion-report-12", className: "blog__image" },
                                            React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/content/8816657811058a2b0ec9c7caa53ef519.800.450.jpg" }),
                                            React.createElement("h1", { className: "blog__title" }, "charity: water Completion Report #12")),
                                        React.createElement("p", { className: "meta" },
                                            "Posted Dec. 25, 2019 by ",
                                            React.createElement("a", { href: "/user/philip/" }, "philip")),
                                        React.createElement("p", null,
                                            "Our twelfth ",
                                            React.createElement("a", { href: "https://charitywater.org" }, "charity: water"),
                                            " completion report arrived! Thanks to your support, we were able to fund 14 water projects in the Maradi Region of Niger serving 6,062 people."),
                                        React.createElement("a", { href: "/blog/162/charity-water-completion-report-12#comments", className: "blog__link--comments" },
                                            React.createElement("svg", { className: "icon shape-comment" },
                                                React.createElement("use", { xlinkHref: "#shape-comment" })),
                                            "25")),
                                    React.createElement("li", { className: "blogGroup" },
                                        React.createElement("a", { href: "/blog/161/laptops-added-to-pcpartpicker", className: "blog__image" },
                                            React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/content/d595291786238f15449d21458b1f229e.jpg" }),
                                            React.createElement("h1", { className: "blog__title" }, "Laptops Added to PCPartPicker")),
                                        React.createElement("p", { className: "meta" },
                                            "Posted Nov. 22, 2019 by ",
                                            React.createElement("a", { href: "/user/philip/" }, "philip")),
                                        React.createElement("p", null,
                                            "Today we're pleased to announce that PCPartPicker is now listing ",
                                            React.createElement("a", { href: "/products/laptop/" }, "traditional and 2-in-1 laptops"),
                                            "."),
                                        React.createElement("a", { href: "/blog/161/laptops-added-to-pcpartpicker#comments", className: "blog__link--comments" },
                                            React.createElement("svg", { className: "icon shape-comment" },
                                                React.createElement("use", { xlinkHref: "#shape-comment" })),
                                            "49"))),
                                React.createElement("div", { className: "blog__button" },
                                    React.createElement("a", { href: "/blog/", className: "button button--small" }, "See More Blog Posts")))))))));
    };
    return HomePage;
}(react_1.Component));
exports.default = HomePage;
//# sourceMappingURL=HomePage.js.map