"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_1 = require("react");
var BrowseProducts = /** @class */ (function (_super) {
    __extends(BrowseProducts, _super);
    function BrowseProducts(props) {
        var _this = _super.call(this, props) || this;
        _this.state = {};
        return _this;
    }
    BrowseProducts.prototype.render = function () {
        return (React.createElement("div", { className: "wrapper wrapper__pageContent " },
            React.createElement("section", { className: "xs-col-11 xs-mx-auto" },
                React.createElement("div", { className: "wrapper--columns" },
                    React.createElement("div", { className: "main-content" },
                        React.createElement("div", { className: "productList block" },
                            React.createElement("div", { className: "productList__breadcrumbs" }),
                            React.createElement("div", { className: "subTitle" },
                                React.createElement("div", { className: "subTitle__header xs-col-12" },
                                    React.createElement("h2", { className: "pp-filter-count" }, "1260 Compatible Products")),
                                React.createElement("div", { className: "subTitle__form" },
                                    React.createElement("form", { className: "form__sort--products" },
                                        React.createElement("label", { className: "form-label xs-inline" }, "Sort by"),
                                        React.createElement("select", { className: "select xs-inline", id: "sort_options2" },
                                            React.createElement("option", { value: "popular" }, "Most Popular"),
                                            React.createElement("option", { value: "name" }, "Name (Ascending)"),
                                            React.createElement("option", { value: "-name" }, "Name (Descending)"),
                                            React.createElement("option", { value: "price" }, "Price (Lowest To Highest)"),
                                            React.createElement("option", { value: "-price" }, "Price (Highest To Lowest)"),
                                            React.createElement("option", { value: "rating" }, "Rating (Lowest To Highest)"),
                                            React.createElement("option", { value: "-rating" }, "Rating (Highest To Lowest)"),
                                            React.createElement("option", { value: "cores" }, "Core Count (Ascending)"),
                                            React.createElement("option", { value: "-cores" }, "Core Count (Descending)"),
                                            React.createElement("option", { value: "clock" }, "Core Clock (Ascending)"),
                                            React.createElement("option", { value: "-clock" }, "Core Clock (Descending)"),
                                            React.createElement("option", { value: "boostclock" }, "Boost Clock (Ascending)"),
                                            React.createElement("option", { value: "-boostclock" }, "Boost Clock (Descending)"),
                                            React.createElement("option", { value: "tdp" }, "TDP (Ascending)"),
                                            React.createElement("option", { value: "-tdp" }, "TDP (Descending)"),
                                            React.createElement("option", { value: "graphics" }, "Integrated Graphics (Ascending)"),
                                            React.createElement("option", { value: "-graphics" }, "Integrated Graphics (Descending)"),
                                            React.createElement("option", { value: "smt" }, "SMT (Ascending)"),
                                            React.createElement("option", { value: "-smt" }, "SMT (Descending)"))),
                                    React.createElement("form", { className: "form__search--products" },
                                        React.createElement("label", { className: "form-label xs-inline" },
                                            React.createElement("svg", { className: "icon shape-search" },
                                                React.createElement("use", { xlinkHref: "#shape-search" }))),
                                        React.createElement("input", { type: "text", className: "text-input inactive_search", placeholder: "CPUs", id: "part_category_search" })))),
                            React.createElement("div", { className: "productList__actions clearfix" },
                                React.createElement("div", { className: "productList__actions--left col xs-col-12 md-col-6" },
                                    React.createElement("a", { href: "#", className: "productList__actions--all", id: "select_all" }, "Select All"),
                                    React.createElement("a", { href: "#", className: "productList__actions--clear disabled", id: "clear_selected" }, "Select None"),
                                    React.createElement("a", { href: "#", className: "productList__actions--compare disabled", id: "compare_selected" }, "Compare Selected")),
                                React.createElement("div", { className: "productList__actions--right col xs-col-12 md-col-6" },
                                    React.createElement("a", { href: "#", className: "productList__actions--setPriceAlert", id: "parametric_add_price_alert_button" }, "Set Price Alert"),
                                    React.createElement("a", { href: "#", className: "productList__actions--addFromFilter button button--small", id: "parametric_add_button" }, "Add From Filter"))),
                            React.createElement("div", { className: "productList__wrapper" },
                                React.createElement("div", { className: "productList__cover" }),
                                React.createElement("table", { className: "productList--detailed xs-col-12 tablesorter tablesorter-default", id: "paginated_table", role: "grid" },
                                    React.createElement("thead", null,
                                        React.createElement("tr", { role: "row", className: "tablesorter-headerRow" },
                                            React.createElement("th", { className: "th__checkbox tablesorter-header sorter-false tablesorter-headerUnSorted th--unsorted", "data-column": 0, tabIndex: 0, scope: "col", role: "columnheader", "aria-disabled": "true", unselectable: "on", "aria-sort": "none", style: { userSelect: 'none' } },
                                                React.createElement("div", { className: "tablesorter-header-inner" })),
                                            React.createElement("th", { className: "th--sortable tablesorter-header tablesorter-headerUnSorted th--unsorted", "data-column": 1, tabIndex: 0, scope: "col", role: "columnheader", "aria-disabled": "false", "aria-controls": "paginated_table", unselectable: "on", "aria-sort": "none", "aria-label": "Name: No sort applied, activate to apply an ascending sort", style: { userSelect: 'none' } },
                                                React.createElement("div", { className: "tablesorter-header-inner" },
                                                    React.createElement("span", { className: "sortArrow sortArrow--down" },
                                                        React.createElement("svg", { className: "icon shape-dropdown-arrow" },
                                                            React.createElement("use", { xlinkHref: "#shape-dropdown-arrow" }))),
                                                    React.createElement("p", null, "Name"))),
                                            React.createElement("th", { className: "th--sortable tablesorter-header tablesorter-headerUnSorted th--unsorted", "data-column": 2, tabIndex: 0, scope: "col", role: "columnheader", "aria-disabled": "false", "aria-controls": "paginated_table", unselectable: "on", "aria-sort": "none", "aria-label": "Core Count: No sort applied, activate to apply an ascending sort", style: { userSelect: 'none' } },
                                                React.createElement("div", { className: "tablesorter-header-inner" },
                                                    React.createElement("span", { className: "sortArrow sortArrow--down" },
                                                        React.createElement("svg", { className: "icon shape-dropdown-arrow" },
                                                            React.createElement("use", { xlinkHref: "#shape-dropdown-arrow" }))),
                                                    React.createElement("p", null, "Core Count"))),
                                            React.createElement("th", { className: "th--sortable tablesorter-header tablesorter-headerUnSorted th--unsorted", "data-column": 3, tabIndex: 0, scope: "col", role: "columnheader", "aria-disabled": "false", "aria-controls": "paginated_table", unselectable: "on", "aria-sort": "none", "aria-label": "Core Clock: No sort applied, activate to apply an ascending sort", style: { userSelect: 'none' } },
                                                React.createElement("div", { className: "tablesorter-header-inner" },
                                                    React.createElement("span", { className: "sortArrow sortArrow--down" },
                                                        React.createElement("svg", { className: "icon shape-dropdown-arrow" },
                                                            React.createElement("use", { xlinkHref: "#shape-dropdown-arrow" }))),
                                                    React.createElement("p", null, "Core Clock"))),
                                            React.createElement("th", { className: "th--sortable tablesorter-header tablesorter-headerUnSorted th--unsorted", "data-column": 4, tabIndex: 0, scope: "col", role: "columnheader", "aria-disabled": "false", "aria-controls": "paginated_table", unselectable: "on", "aria-sort": "none", "aria-label": "Boost Clock: No sort applied, activate to apply an ascending sort", style: { userSelect: 'none' } },
                                                React.createElement("div", { className: "tablesorter-header-inner" },
                                                    React.createElement("span", { className: "sortArrow sortArrow--down" },
                                                        React.createElement("svg", { className: "icon shape-dropdown-arrow" },
                                                            React.createElement("use", { xlinkHref: "#shape-dropdown-arrow" }))),
                                                    React.createElement("p", null, "Boost Clock"))),
                                            React.createElement("th", { className: "th--sortable tablesorter-header tablesorter-headerUnSorted th--unsorted", "data-column": 5, tabIndex: 0, scope: "col", role: "columnheader", "aria-disabled": "false", "aria-controls": "paginated_table", unselectable: "on", "aria-sort": "none", "aria-label": "TDP: No sort applied, activate to apply an ascending sort", style: { userSelect: 'none' } },
                                                React.createElement("div", { className: "tablesorter-header-inner" },
                                                    React.createElement("span", { className: "sortArrow sortArrow--down" },
                                                        React.createElement("svg", { className: "icon shape-dropdown-arrow" },
                                                            React.createElement("use", { xlinkHref: "#shape-dropdown-arrow" }))),
                                                    React.createElement("p", null, "TDP"))),
                                            React.createElement("th", { className: "th--sortable tablesorter-header tablesorter-headerUnSorted th--unsorted", "data-column": 6, tabIndex: 0, scope: "col", role: "columnheader", "aria-disabled": "false", "aria-controls": "paginated_table", unselectable: "on", "aria-sort": "none", "aria-label": "Integrated Graphics: No sort applied, activate to apply an ascending sort", style: { userSelect: 'none' } },
                                                React.createElement("div", { className: "tablesorter-header-inner" },
                                                    React.createElement("span", { className: "sortArrow sortArrow--down" },
                                                        React.createElement("svg", { className: "icon shape-dropdown-arrow" },
                                                            React.createElement("use", { xlinkHref: "#shape-dropdown-arrow" }))),
                                                    React.createElement("p", null, "Integrated Graphics"))),
                                            React.createElement("th", { className: "th--sortable tablesorter-header tablesorter-headerUnSorted th--unsorted", "data-column": 7, tabIndex: 0, scope: "col", role: "columnheader", "aria-disabled": "false", "aria-controls": "paginated_table", unselectable: "on", "aria-sort": "none", "aria-label": "SMT: No sort applied, activate to apply an ascending sort", style: { userSelect: 'none' } },
                                                React.createElement("div", { className: "tablesorter-header-inner" },
                                                    React.createElement("span", { className: "sortArrow sortArrow--down" },
                                                        React.createElement("svg", { className: "icon shape-dropdown-arrow" },
                                                            React.createElement("use", { xlinkHref: "#shape-dropdown-arrow" }))),
                                                    React.createElement("p", null, "SMT"))),
                                            React.createElement("th", { className: "th--sortable tablesorter-header tablesorter-headerUnSorted th--unsorted", "data-column": 8, tabIndex: 0, scope: "col", role: "columnheader", "aria-disabled": "false", "aria-controls": "paginated_table", unselectable: "on", "aria-sort": "none", "aria-label": "Rating: No sort applied, activate to apply an ascending sort", style: { userSelect: 'none' } },
                                                React.createElement("div", { className: "tablesorter-header-inner" },
                                                    React.createElement("span", { className: "sortArrow sortArrow--down" },
                                                        React.createElement("svg", { className: "icon shape-dropdown-arrow" },
                                                            React.createElement("use", { xlinkHref: "#shape-dropdown-arrow" }))),
                                                    React.createElement("p", null, "Rating"))),
                                            React.createElement("th", { className: "th--sortable th__price tablesorter-header tablesorter-headerUnSorted th--unsorted", "data-column": 9, tabIndex: 0, scope: "col", role: "columnheader", "aria-disabled": "false", "aria-controls": "paginated_table", unselectable: "on", "aria-sort": "none", "aria-label": "Price: No sort applied, activate to apply an ascending sort", style: { userSelect: 'none' } },
                                                React.createElement("div", { className: "tablesorter-header-inner" },
                                                    React.createElement("span", { className: "sortArrow sortArrow--up" },
                                                        React.createElement("svg", { className: "icon shape-dropdown-arrow" },
                                                            React.createElement("use", { xlinkHref: "#shape-dropdown-arrow" }))),
                                                    React.createElement("p", null, "Price"))))),
                                    React.createElement("tbody", { id: "category_content", "aria-live": "polite", "aria-relevant": "all" },
                                        React.createElement("tr", { className: "tr__product", id: "pb_244375", "data-pb-id": 244375 },
                                            "  ",
                                            React.createElement("td", { className: "td__checkbox" },
                                                "    ",
                                                React.createElement("input", { type: "checkbox", className: "checkbox px px1", id: "px_244375", autoComplete: "off" }),
                                                "    ",
                                                React.createElement("label", { htmlFor: "px_244375" })),
                                            "  ",
                                            React.createElement("td", { className: "td__name" },
                                                "    ",
                                                React.createElement("div", { className: "div__checkbox" },
                                                    React.createElement("input", { type: "checkbox", className: "checkbox px px2", id: "px2_244375", autoComplete: "off" }),
                                                    React.createElement("label", { htmlFor: "px2_244375" })),
                                                "    ",
                                                React.createElement("a", { href: "/product/9nm323/amd-ryzen-5-3600-36-thz-6-core-processor-100-100000031box" },
                                                    "      ",
                                                    React.createElement("div", { className: "td__imageWrapper" },
                                                        "        ",
                                                        React.createElement("div", { className: "td__image" },
                                                            "          ",
                                                            React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/product/c7baf2c9c9cc15ae23adb24c2f4316fc.256p.jpg" }),
                                                            "          ",
                                                            React.createElement("div", { className: "td__image--lg" },
                                                                "            ",
                                                                React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/product/c7baf2c9c9cc15ae23adb24c2f4316fc.256p.jpg" }),
                                                                "        "),
                                                            "      "),
                                                        "    "),
                                                    "      ",
                                                    React.createElement("div", { className: "td__nameWrapper" },
                                                        "      ",
                                                        React.createElement("p", null, "AMD Ryzen 5 3600"),
                                                        "        ",
                                                        React.createElement("div", { className: "td__rating", "data-ci": 982 },
                                                            React.createElement("ul", { className: "product--rating list-unstyled" },
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-half" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-half" })))),
                                                            " (748)"),
                                                        "    "),
                                                    "  ")),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--1" },
                                                React.createElement("h6", { className: "specLabel" }, "Core Count"),
                                                "6"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--2" },
                                                React.createElement("h6", { className: "specLabel" }, "Core Clock"),
                                                "3.6 GHz"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--3" },
                                                React.createElement("h6", { className: "specLabel" }, "Boost Clock"),
                                                "4.2 GHz"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--4" },
                                                React.createElement("h6", { className: "specLabel" }, "TDP"),
                                                "65 W"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--5" },
                                                React.createElement("h6", { className: "specLabel" }, "Integrated Graphics"),
                                                "None"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--6" },
                                                React.createElement("h6", { className: "specLabel" }, "SMT"),
                                                "Yes"),
                                            "  ",
                                            React.createElement("td", { className: "td__rating td--nowrap", "data-ci": 982 },
                                                React.createElement("ul", { className: "product--rating list-unstyled" },
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-half" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-half" })))),
                                                " (748)"),
                                            "  ",
                                            React.createElement("td", { className: "td__price" },
                                                "$342.10",
                                                React.createElement("button", { className: "td__add button button--small pp_add_part", "data-product-tag": "9nm323", "data-product-location": true }, "Add"))),
                                        React.createElement("tr", { className: "tr__product", id: "pb_329299", "data-pb-id": 329299 },
                                            "  ",
                                            React.createElement("td", { className: "td__checkbox" },
                                                "    ",
                                                React.createElement("input", { type: "checkbox", className: "checkbox px px1", id: "px_329299", autoComplete: "off" }),
                                                "    ",
                                                React.createElement("label", { htmlFor: "px_329299" })),
                                            "  ",
                                            React.createElement("td", { className: "td__name" },
                                                "    ",
                                                React.createElement("div", { className: "div__checkbox" },
                                                    React.createElement("input", { type: "checkbox", className: "checkbox px px2", id: "px2_329299", autoComplete: "off" }),
                                                    React.createElement("label", { htmlFor: "px2_329299" })),
                                                "    ",
                                                React.createElement("a", { href: "/product/KwLwrH/amd-ryzen-9-5900x-37-ghz-12-core-processor-100-100000061wof" },
                                                    "      ",
                                                    React.createElement("div", { className: "td__imageWrapper" },
                                                        "        ",
                                                        React.createElement("div", { className: "td__image" },
                                                            "          ",
                                                            React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/product/1d7073a2deda3bd22963a7e248bbe3e4.256p.jpg" }),
                                                            "          ",
                                                            React.createElement("div", { className: "td__image--lg" },
                                                                "            ",
                                                                React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/product/1d7073a2deda3bd22963a7e248bbe3e4.256p.jpg" }),
                                                                "        "),
                                                            "      "),
                                                        "    "),
                                                    "      ",
                                                    React.createElement("div", { className: "td__nameWrapper" },
                                                        "      ",
                                                        React.createElement("p", null, "AMD Ryzen 9 5900X"),
                                                        "        ",
                                                        React.createElement("div", { className: "td__rating", "data-ci": 912 },
                                                            React.createElement("ul", { className: "product--rating list-unstyled" },
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" })))),
                                                            " (8)"),
                                                        "    "),
                                                    "  ")),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--1" },
                                                React.createElement("h6", { className: "specLabel" }, "Core Count"),
                                                "12"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--2" },
                                                React.createElement("h6", { className: "specLabel" }, "Core Clock"),
                                                "3.7 GHz"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--3" },
                                                React.createElement("h6", { className: "specLabel" }, "Boost Clock"),
                                                "4.8 GHz"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--4" },
                                                React.createElement("h6", { className: "specLabel" }, "TDP"),
                                                "105 W"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--5" },
                                                React.createElement("h6", { className: "specLabel" }, "Integrated Graphics"),
                                                "None"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--6" },
                                                React.createElement("h6", { className: "specLabel" }, "SMT"),
                                                "Yes"),
                                            "  ",
                                            React.createElement("td", { className: "td__rating td--nowrap", "data-ci": 912 },
                                                React.createElement("ul", { className: "product--rating list-unstyled" },
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" })))),
                                                " (8)"),
                                            "  ",
                                            React.createElement("td", { className: "td__price" },
                                                React.createElement("button", { className: "td__add button button--small pp_add_part", "data-product-tag": "KwLwrH", "data-product-location": true }, "Add"))),
                                        React.createElement("tr", { className: "tr__product", id: "pb_199831", "data-pb-id": 199831 },
                                            "  ",
                                            React.createElement("td", { className: "td__checkbox" },
                                                "    ",
                                                React.createElement("input", { type: "checkbox", className: "checkbox px px1", id: "px_199831", autoComplete: "off" }),
                                                "    ",
                                                React.createElement("label", { htmlFor: "px_199831" })),
                                            "  ",
                                            React.createElement("td", { className: "td__name" },
                                                "    ",
                                                React.createElement("div", { className: "div__checkbox" },
                                                    React.createElement("input", { type: "checkbox", className: "checkbox px px2", id: "px2_199831", autoComplete: "off" }),
                                                    React.createElement("label", { htmlFor: "px2_199831" })),
                                                "    ",
                                                React.createElement("a", { href: "/product/jHZFf7/intel-core-i9-9900k-36ghz-8-core-processor-bx80684i99900k" },
                                                    "      ",
                                                    React.createElement("div", { className: "td__imageWrapper" },
                                                        "        ",
                                                        React.createElement("div", { className: "td__image" },
                                                            "          ",
                                                            React.createElement("img", { src: "https://images-na.ssl-images-amazon.com/images/I/41EDFtP5hpL.jpg" }),
                                                            "          ",
                                                            React.createElement("div", { className: "td__image--lg" },
                                                                "            ",
                                                                React.createElement("img", { src: "https://images-na.ssl-images-amazon.com/images/I/41EDFtP5hpL.jpg" }),
                                                                "        "),
                                                            "      "),
                                                        "    "),
                                                    "      ",
                                                    React.createElement("div", { className: "td__nameWrapper" },
                                                        "      ",
                                                        React.createElement("p", null, "Intel Core i9-9900K"),
                                                        "        ",
                                                        React.createElement("div", { className: "td__rating", "data-ci": 957 },
                                                            React.createElement("ul", { className: "product--rating list-unstyled" },
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-half" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-half" })))),
                                                            " (177)"),
                                                        "    "),
                                                    "  ")),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--1" },
                                                React.createElement("h6", { className: "specLabel" }, "Core Count"),
                                                "8"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--2" },
                                                React.createElement("h6", { className: "specLabel" }, "Core Clock"),
                                                "3.6 GHz"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--3" },
                                                React.createElement("h6", { className: "specLabel" }, "Boost Clock"),
                                                "5 GHz"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--4" },
                                                React.createElement("h6", { className: "specLabel" }, "TDP"),
                                                "95 W"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--5" },
                                                React.createElement("h6", { className: "specLabel" }, "Integrated Graphics"),
                                                "Intel UHD Graphics 630"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--6" },
                                                React.createElement("h6", { className: "specLabel" }, "SMT"),
                                                "Yes"),
                                            "  ",
                                            React.createElement("td", { className: "td__rating td--nowrap", "data-ci": 957 },
                                                React.createElement("ul", { className: "product--rating list-unstyled" },
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-half" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-half" })))),
                                                " (177)"),
                                            "  ",
                                            React.createElement("td", { className: "td__price" },
                                                "$339.99",
                                                React.createElement("button", { className: "td__add button button--small pp_add_part", "data-product-tag": "jHZFf7", "data-product-location": true }, "Add"))),
                                        React.createElement("tr", { className: "tr__product", id: "pb_81645", "data-pb-id": 81645 },
                                            "  ",
                                            React.createElement("td", { className: "td__checkbox" },
                                                "    ",
                                                React.createElement("input", { type: "checkbox", className: "checkbox px px1", id: "px_81645", autoComplete: "off" }),
                                                "    ",
                                                React.createElement("label", { htmlFor: "px_81645" })),
                                            "  ",
                                            React.createElement("td", { className: "td__name" },
                                                "    ",
                                                React.createElement("div", { className: "div__checkbox" },
                                                    React.createElement("input", { type: "checkbox", className: "checkbox px px2", id: "px2_81645", autoComplete: "off" }),
                                                    React.createElement("label", { htmlFor: "px2_81645" })),
                                                "    ",
                                                React.createElement("a", { href: "/product/dQM323/intel-core-i5-7600k-38ghz-quad-core-processor-bx80677i57600k" },
                                                    "      ",
                                                    React.createElement("div", { className: "td__imageWrapper" },
                                                        "        ",
                                                        React.createElement("div", { className: "td__image" },
                                                            "          ",
                                                            React.createElement("img", { src: "https://images-na.ssl-images-amazon.com/images/I/51OwhiuFloL.jpg" }),
                                                            "          ",
                                                            React.createElement("div", { className: "td__image--lg" },
                                                                "            ",
                                                                React.createElement("img", { src: "https://images-na.ssl-images-amazon.com/images/I/51OwhiuFloL.jpg" }),
                                                                "        "),
                                                            "      "),
                                                        "    "),
                                                    "      ",
                                                    React.createElement("div", { className: "td__nameWrapper" },
                                                        "      ",
                                                        React.createElement("p", null, "Intel Core i5-7600K"),
                                                        "        ",
                                                        React.createElement("div", { className: "td__rating", "data-ci": 953 },
                                                            React.createElement("ul", { className: "product--rating list-unstyled" },
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-half" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-half" })))),
                                                            " (136)"),
                                                        "    "),
                                                    "  ")),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--1" },
                                                React.createElement("h6", { className: "specLabel" }, "Core Count"),
                                                "4"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--2" },
                                                React.createElement("h6", { className: "specLabel" }, "Core Clock"),
                                                "3.8 GHz"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--3" },
                                                React.createElement("h6", { className: "specLabel" }, "Boost Clock"),
                                                "4.2 GHz"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--4" },
                                                React.createElement("h6", { className: "specLabel" }, "TDP"),
                                                "91 W"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--5" },
                                                React.createElement("h6", { className: "specLabel" }, "Integrated Graphics"),
                                                "Intel HD Graphics 630"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--6" },
                                                React.createElement("h6", { className: "specLabel" }, "SMT"),
                                                "No"),
                                            "  ",
                                            React.createElement("td", { className: "td__rating td--nowrap", "data-ci": 953 },
                                                React.createElement("ul", { className: "product--rating list-unstyled" },
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-half" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-half" })))),
                                                " (136)"),
                                            "  ",
                                            React.createElement("td", { className: "td__price" },
                                                "$319.75",
                                                React.createElement("button", { className: "td__add button button--small pp_add_part", "data-product-tag": "dQM323", "data-product-location": true }, "Add"))),
                                        React.createElement("tr", { className: "tr__product", id: "pb_102157", "data-pb-id": 102157 },
                                            "  ",
                                            React.createElement("td", { className: "td__checkbox" },
                                                "    ",
                                                React.createElement("input", { type: "checkbox", className: "checkbox px px1", id: "px_102157", autoComplete: "off" }),
                                                "    ",
                                                React.createElement("label", { htmlFor: "px_102157" })),
                                            "  ",
                                            React.createElement("td", { className: "td__name" },
                                                "    ",
                                                React.createElement("div", { className: "div__checkbox" },
                                                    React.createElement("input", { type: "checkbox", className: "checkbox px px2", id: "px2_102157", autoComplete: "off" }),
                                                    React.createElement("label", { htmlFor: "px2_102157" })),
                                                "    ",
                                                React.createElement("a", { href: "/product/8hwqqs/amd-ryzen-5-1600x-36ghz-6-core-processor-yd160xbcaewof" },
                                                    "      ",
                                                    React.createElement("div", { className: "td__imageWrapper" },
                                                        "        ",
                                                        React.createElement("div", { className: "td__image" },
                                                            "          ",
                                                            React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/product/62069eabe77fa79c55158028545484f2.256p.jpg" }),
                                                            "          ",
                                                            React.createElement("div", { className: "td__image--lg" },
                                                                "            ",
                                                                React.createElement("img", { src: "//cdna.pcpartpicker.com/static/forever/images/product/62069eabe77fa79c55158028545484f2.256p.jpg" }),
                                                                "        "),
                                                            "      "),
                                                        "    "),
                                                    "      ",
                                                    React.createElement("div", { className: "td__nameWrapper" },
                                                        "      ",
                                                        React.createElement("p", null, "AMD Ryzen 5 1600X"),
                                                        "        ",
                                                        React.createElement("div", { className: "td__rating", "data-ci": 964 },
                                                            React.createElement("ul", { className: "product--rating list-unstyled" },
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-full" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                                React.createElement("li", null,
                                                                    React.createElement("svg", { className: "icon shape-star-half" },
                                                                        React.createElement("use", { xlinkHref: "#shape-star-half" })))),
                                                            " (73)"),
                                                        "    "),
                                                    "  ")),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--1" },
                                                React.createElement("h6", { className: "specLabel" }, "Core Count"),
                                                "6"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--2" },
                                                React.createElement("h6", { className: "specLabel" }, "Core Clock"),
                                                "3.6 GHz"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--3" },
                                                React.createElement("h6", { className: "specLabel" }, "Boost Clock"),
                                                "4 GHz"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--4" },
                                                React.createElement("h6", { className: "specLabel" }, "TDP"),
                                                "95 W"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--5" },
                                                React.createElement("h6", { className: "specLabel" }, "Integrated Graphics"),
                                                "None"),
                                            "  ",
                                            React.createElement("td", { className: "td__spec td__spec--6" },
                                                React.createElement("h6", { className: "specLabel" }, "SMT"),
                                                "Yes"),
                                            "  ",
                                            React.createElement("td", { className: "td__rating td--nowrap", "data-ci": 964 },
                                                React.createElement("ul", { className: "product--rating list-unstyled" },
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-full" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-full" }))),
                                                    React.createElement("li", null,
                                                        React.createElement("svg", { className: "icon shape-star-half" },
                                                            React.createElement("use", { xlinkHref: "#shape-star-half" })))),
                                                " (73)"),
                                            "  ",
                                            React.createElement("td", { className: "td__price" },
                                                "$262.60",
                                                React.createElement("button", { className: "td__add button button--small pp_add_part", "data-product-tag": "8hwqqs", "data-product-location": true }, "Add"))))))),
                        React.createElement("div", { className: "block", id: "page_button_row_bot" },
                            React.createElement("section", { id: "module-pagination" },
                                React.createElement("ul", { className: "pagination list-unstyled xs-text-center" },
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "#page=1", className: "pagination--current" }, "1")),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "#page=2" }, "2")),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "#page=3" }, "3")),
                                    React.createElement("li", null, "\u00B7"),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "#page=10" }, "10")),
                                    React.createElement("li", null, "\u00B7"),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "#page=13" }, "13"))))))))));
    };
    return BrowseProducts;
}(react_1.Component));
exports.default = BrowseProducts;
//# sourceMappingURL=BrowseProducts.js.map